### ISSUE TITLE
关于Haze-4K数据集的训练资源

### ISSUE THREAD

**Issue by 154115081020** [IDKiro/gUNet#10]
请问作者使用Haze-4k数据集训练模型时用了多少张显卡，多长时间？
期待您的答复

**Comment by IDKiro** [comment]
3090 * 4，gUNet-T大概一天？具体我自己也忘了，这篇论文被拒之后已经放弃了

**Comment by IDKiro** [comment]
repo里面提供了训练的log，可以打开看看时间戳
