### ISSUE TITLE
数据读取

### ISSUE THREAD

**Issue by liu0619** [IDKiro/gUNet#12]
您好，想问一下您 这下边的这个报错是什么问题呢？ 
File "/data1/lyl/gUNet-main/utils/common.py", line 52, in read_img
    return img[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable
非常希望得到您的回复，感谢

**Comment by IDKiro** [comment]
应该是你的数据集路径设置错了，你用断点调试或者打印看看loader.py的文件名列表是不是空的

**Comment by MaiheZHao** [comment]
你好，请问你解决了吗
