### ISSUE TITLE
The question about size of the input image.

### ISSUE THREAD

**Issue by 17328-wu** [IDKiro/gUNet#3]
Thank you very much for your sharing!
The following error occurred when I entered an image size of 412*548:
    in_feats = torch.cat(in_feats, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 102 but got size 103 for tensor number 1 in the list.

What is the reason for this problem？How should I predict dehaze images?
Looking forward to your reply！

**Comment by IDKiro** [comment]
Which model did you use？
When inferring, the input image is padded in line 56 in 'test.py'

```
input = pad_img(input, network.patch_size if hasattr(network, 'patch_size') else 16)
```

**Comment by 17328-wu** [comment]
> Which model did you use？ When inferring, the input image is padded in line 56 in 'test.py'
> 
> ```
> input = pad_img(input, network.patch_size if hasattr(network, 'patch_size') else 16)
> ```

I uesd gunet_d() model.

**Comment by 17328-wu** [comment]
> Which model did you use？ When inferring, the input image is padded in line 56 in 'test.py'
> 
> ```
> input = pad_img(input, network.patch_size if hasattr(network, 'patch_size') else 16)
> ```

thank you!  The problem is solved!

**Comment by IDKiro** [comment]
Glad to help you
