### ISSUE TITLE
Why downSample is using 3*3 conv in paper framework, but i don't see kernel=3 in code? 

### ISSUE THREAD

**Issue by AmeryXiong** [IDKiro/gUNet#5]
![image](https://user-images.githubusercontent.com/102467128/200779969-97380d1c-1821-463b-8b2e-ca8607f3955c.png)
![image](https://user-images.githubusercontent.com/102467128/200780082-45d5e4cc-af52-43e0-9686-7f0fb208aa64.png)
![image](https://user-images.githubusercontent.com/102467128/200780234-4147da82-5bf3-4517-8599-e26b01ddfd05.png)

Why downSample is using 3*3 conv in paper framework, but i don't see kernel=3 in code?

**Comment by IDKiro** [comment]
I checked and found that the figure was wrong, thank you very much for the reminder.

**Comment by IDKiro** [comment]
I have updated the figure in the repo, the figure of the paper will be updated after that paper is accepted, thanks again for the reminder.
