### ISSUE TITLE
Baselines?

### ISSUE THREAD

**Issue by zlou** [IDKiro/gUNet#7]
Hi

Thanks for the interesting work. I saw that there is a ./models/baselines folder in the repo. The paper also mentioned, " All models are trained using their original strategies, and we replicate the best results reported in the previous works". I am wondering if that means you put the models together in this repo and replicated the baselines based on their original training strategies for RESIDE-IN and RESIDE-OUT. And used the same training strategy for RS-Haze if the original work did not use this dataset?

**Comment by IDKiro** [comment]
Yes. I provide the code for baselines to make it easier for beginners.

**Comment by hxu296** [comment]
> Yes. I provide the code for baselines to make it easier for beginners.

Thank you! As a follow up question, would it be possible for you to also share the training config files for baselines, as different baselines may have different training strategies. This effort will help me and potentially others beginners significantly. Thank you again!

**Comment by IDKiro** [comment]
I recently had 2019-nCoV and will probably do an update when I am fully recovered.
You can try copying model_t.json (or model_s.json ...) to use as the config file for baselines. Just set the batch size as large as possible when there is no out of memory (but not more than 256), while the learning rate is scaled according to the linear scaling rule.

**Comment by IDKiro** [comment]
> > Yes. I provide the code for baselines to make it easier for beginners.
> 
> Thank you! As a follow up question, would it be possible for you to also share the training config files for baselines, as different baselines may have different training strategies. This effort will help me and potentially other beginners significantly. Thank you again!

I recently had 2019-nCoV and will probably do an update when I am fully recovered.
You can try copying model_t.json (or model_s.json ...) as the config file for baselines. Just choose the batch size as large as possible when there is no out of memory (but not more than 256), while the learning rate is scaled according to the linear scaling rule.

**Comment by hxu296** [comment]
> > > Yes. I provide the code for baselines to make it easier for beginners.
> > 
> > 
> > Thank you! As a follow up question, would it be possible for you to also share the training config files for baselines, as different baselines may have different training strategies. This effort will help me and potentially other beginners significantly. Thank you again!
> 
> I recently had 2019-nCoV and will probably do an update when I am fully recovered. You can try copying model_t.json (or model_s.json ...) as the config file for baselines. Just choose the batch size as large as possible when there is no out of memory (but not more than 256), while the learning rate is scaled according to the linear scaling rule.

I'm sorry to hear you are ill, and I hope you recover quickly! Thank you for the extra tips.
