### ISSUE TITLE
Why has it been a long time since the progress has not changed during training, and there have been no errors?

### ISSUE THREAD

**Issue by yanghaoRonin** [IDKiro/gUNet#9]
==> Using SyncBN because of too small norm-batch-size.
==> Start training, current model name: gunet_t
  0%|          | 0/501 [00:00<?, ?it/s]

**Comment by IDKiro** [comment]
Your environment (hardware and software)?

**Comment by yanghaoRonin** [comment]
Already solved, is my graphics card is not very good, the speed is too slow

**Comment by IDKiro** [comment]
OK

**Comment by yanghaoRonin** [comment]
Why can't I see any evaluation indicators after training? Can only calculate it yourself

**Comment by IDKiro** [comment]
I didn't understand your question, did you check the tensorboard during training?
